# Disabled for now, to not waste CI resources

name: Cargo tests

on: [ push, pull_request ]

jobs:
  cargo_test:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - uses: actions-rs/toolchain@v1
       with:
         toolchain: 1.58
         target: wasm32-unknown-unknown

     - run: rustup update stable
     - run: rustc --version
     - run: cargo --version
     - run: rustup component list --installed
     - run: rustup show

     - run: ./scripts/happ-test.sh
     - run: cargo install holochain_cli --version 0.1.0 --locked
